In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([1.2,2.2])

In [5]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
print(a.dtype)
print(b.dtype)

int32
float64


In [9]:
a = np.array(1,2,3,4,5,6,7,8,9,10)

TypeError: array() takes from 1 to 2 positional arguments but 10 were given

In [10]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a.ndim

1

In [20]:
a = np.array([(1,2,3,4,5),(6,7,8,9,10)])

In [16]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
a[0]
a[1]

array([ 6,  7,  8,  9, 10])

In [23]:
a.dtype

dtype('int32')

In [24]:
type(a)

numpy.ndarray

In [25]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [26]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
a.dtype

dtype('int32')

In [28]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=complex)

In [29]:
a

array([[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j],
       [ 6.+0.j,  7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j]])

In [34]:
a =np.zeros((3,4))

In [35]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
a.dtype

dtype('float64')

In [37]:
a.ndim

2

In [38]:
b = np.ones((2,3,4),dtype=float)

In [39]:
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [40]:
b.ndim

3

In [43]:
b = np.ones((3,3,4),dtype=float)

In [44]:
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [45]:
b.ndim

3

In [46]:
b = np.ones((3,4,4),dtype=float)

In [47]:
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [48]:
b.ndim

3

In [54]:
b = np.ones((2,3,4,4),dtype=float)

In [55]:
b

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [56]:
b.ndim

4

4 boyutlu bir dizi oluşturmak için np.ones fonksiyonuna 4 boyutlu bir şekil (boyutlar dizisi) belirtmelisiniz. Örneğin, (2, 3, 4, 5) şeklinde bir boyut belirtmek, 4 boyutlu bir dizi oluşturur.

Bu boyutlar şu anlama gelir:

İlk boyut: 2, yani 2 tane 3 boyutlu tensör içerir.
İkinci boyut: 3, yani her tensör 3 tane 2 boyutlu matris içerir.
Üçüncü boyut: 4, yani her matris 4 satıra sahiptir.
Dördüncü boyut: 5, yani her satırda 5 sütun vardır.

In [57]:
np.empty((2,3))

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304]])

In [58]:
x = np.arange(2,30)

In [59]:
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [61]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [62]:
np.sin(np.linspace(0,2,9))

array([0.        , 0.24740396, 0.47942554, 0.68163876, 0.84147098,
       0.94898462, 0.99749499, 0.98398595, 0.90929743])

In [63]:
x = np.array((1,2,3,4,5,6))

In [64]:
x

array([1, 2, 3, 4, 5, 6])

In [65]:
x.ndim

1

In [68]:
x2=x.reshape(3,2)

In [69]:
x2.ndim

2

In [70]:
x = np.arange(0,24)

In [71]:
x.ndim

1

In [73]:
x2=x.reshape(2,3,4)

In [74]:
x2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [75]:
x2.ndim

3

In [76]:
x = np.arange(0,100)

In [77]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [78]:
import  sys
np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

In [79]:
a = np.array([10,20,30,40])
b =np.arange(4)

In [80]:
a

array([10, 20, 30, 40])

In [81]:
b

array([0, 1, 2, 3])

In [82]:
a-b

array([10, 19, 28, 37])

In [83]:
a+b

array([10, 21, 32, 43])

In [85]:
a*b

array([  0,  20,  60, 120])

In [86]:
a/b

C:\Users\rayes\AppData\Local\Temp\ipykernel_26384\3318604225.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([        inf, 20.        , 15.        , 13.33333333])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 0, 2])  # İkinci eleman sıfır

# Bölme işlemi yapmadan önce bölenin sıfır olup olmadığını kontrol et
with np.errstate(divide='ignore', invalid='ignore'):
    result = np.where(b == 0, np.inf, a / b)  # Bölen sıfırsa sonucu sonsuz olarak ayarla

print(result)


In [102]:
a = np.array([[5,10,11],[24,25,26]])

In [103]:
a.shape

(2, 3)

In [104]:
b=np.array([[10,11],[25,26],[2,3]])

In [105]:
b.shape

(3, 2)

In [106]:
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [107]:
b@a

array([[314, 375, 396],
       [749, 900, 951],
       [ 82,  95, 100]])

In [119]:
a = np.arange(10).reshape(5,2)

In [125]:
b = np.arange(24).reshape(2,12)

In [111]:
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 12 is different from 2)

In [122]:
a.shape

(5, 2)

In [123]:
b.shape

(12, 2)

In [126]:
a@b

array([[ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 36,  41,  46,  51,  56,  61,  66,  71,  76,  81,  86,  91],
       [ 60,  69,  78,  87,  96, 105, 114, 123, 132, 141, 150, 159],
       [ 84,  97, 110, 123, 136, 149, 162, 175, 188, 201, 214, 227],
       [108, 125, 142, 159, 176, 193, 210, 227, 244, 261, 278, 295]])

In [127]:
a*b

ValueError: operands could not be broadcast together with shapes (5,2) (2,12) 

In [128]:
x = np.arange(10).reshape(5,2)

In [129]:
np.exp(x)

array([[1.00000000e+00, 2.71828183e+00],
       [7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03]])

In [130]:
x = np.arange(48).reshape(6,8)

In [132]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [131]:
x.sum(axis=1)

array([ 28,  92, 156, 220, 284, 348])

In [133]:
x.sum(axis=0)

array([120, 126, 132, 138, 144, 150, 156, 162])

In [134]:
x.max(axis=1)

array([ 7, 15, 23, 31, 39, 47])

In [135]:
x.min(axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [136]:
np.sqrt(x)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479, 3.46410162,
        3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569, 4.69041576, 4.79583152],
       [4.89897949, 5.        , 5.09901951, 5.19615242, 5.29150262,
        5.38516481, 5.47722558, 5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253, 6.164414  , 6.244998  ],
       [6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
        6.70820393, 6.78232998, 6.8556546 ]])

In [137]:
np.square(x)

array([[   0,    1,    4,    9,   16,   25,   36,   49],
       [  64,   81,  100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841,  900,  961],
       [1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209]])

In [138]:
np.where(0)

C:\Users\rayes\AppData\Local\Temp\ipykernel_26384\3541678379.py:1: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
  np.where(0)


(array([], dtype=int64),)

In [146]:
np.where(x>30,x,0)

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [148]:
np.all(x>=0)

True

In [149]:
np.any(x>0)

True

In [150]:
np.any(x<0)

False

In [160]:
np.any(x==16,axis=1)

array([False, False,  True, False, False, False])

In [156]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
#all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

In [162]:
a = np.arange(15)**2

In [163]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [164]:
a[0]

0

In [165]:
a[1:5]

array([ 1,  4,  9, 16])

In [166]:
import numpy as np

result = np.fromfunction(lambda i, j: i + j, (3, 3))
print(result)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [167]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)

In [168]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [169]:
b[-1]

array([40, 41, 42, 43])

In [170]:
b[1]

array([10, 11, 12, 13])

In [171]:
b[-2]

array([30, 31, 32, 33])

In [172]:
b[0,1]

1

In [173]:
b[0]

array([0, 1, 2, 3])

In [174]:
x = np.arange(24).reshape(2,3,4)

In [175]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [177]:
x[0][0]

array([0, 1, 2, 3])

In [178]:
x[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [181]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [182]:
toplam=0
for i in x.flatten():
    toplam+=i

In [183]:
print(toplam)

276


In [185]:
x = np.arange(24).reshape(2,3,4)
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [187]:
x = np.linspace(0,27,3)

In [188]:
x

array([ 0. , 13.5, 27. ])

In [189]:
np.floor(x)

array([ 0., 13., 27.])

In [190]:
x

array([ 0. , 13.5, 27. ])

In [191]:
x = np.arange(24).reshape(2,3,4)

In [192]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [194]:
x.transpose().shape

(4, 3, 2)

In [195]:
x.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [196]:
x = np.arange(24).reshape(6,4)

In [197]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [198]:
x.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [199]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [201]:
x.resize(2,12)

In [202]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [203]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [205]:
x.reshape(3,-1)  # sona -1 atarsak otomatik atar

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [206]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

In [207]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [208]:
np.hstack((a,b)) #yatay

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [209]:
np.vstack((a,b)) #dikey vertical

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [210]:
from numpy import newaxis

In [211]:
a = np.array([1,2,3,4,5,6])

In [212]:
a

array([1, 2, 3, 4, 5, 6])

In [215]:
b = a[:, newaxis]

In [217]:
b.ndim

2

In [218]:
a.ndim

1

In [219]:
b.shape

(6, 1)

In [220]:
a.shape

(6,)

In [224]:
a = np.array([3,4])
b = np.array([5,6])

c = np.column_stack((a,b))

In [223]:
a.ndim

1

In [225]:
c

array([[3, 5],
       [4, 6]])

In [226]:
c.ndim

2

In [227]:
a = np.arange(24).reshape(2,3,4)
b = np.linspace(15,30,24).reshape(2,3,4)

In [228]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [229]:
b

array([[[15.        , 15.65217391, 16.30434783, 16.95652174],
        [17.60869565, 18.26086957, 18.91304348, 19.56521739],
        [20.2173913 , 20.86956522, 21.52173913, 22.17391304]],

       [[22.82608696, 23.47826087, 24.13043478, 24.7826087 ],
        [25.43478261, 26.08695652, 26.73913043, 27.39130435],
        [28.04347826, 28.69565217, 29.34782609, 30.        ]]])

In [231]:
d = np.column_stack((a,b))

In [232]:
d

array([[[ 0.        ,  1.        ,  2.        ,  3.        ],
        [ 4.        ,  5.        ,  6.        ,  7.        ],
        [ 8.        ,  9.        , 10.        , 11.        ],
        [15.        , 15.65217391, 16.30434783, 16.95652174],
        [17.60869565, 18.26086957, 18.91304348, 19.56521739],
        [20.2173913 , 20.86956522, 21.52173913, 22.17391304]],

       [[12.        , 13.        , 14.        , 15.        ],
        [16.        , 17.        , 18.        , 19.        ],
        [20.        , 21.        , 22.        , 23.        ],
        [22.82608696, 23.47826087, 24.13043478, 24.7826087 ],
        [25.43478261, 26.08695652, 26.73913043, 27.39130435],
        [28.04347826, 28.69565217, 29.34782609, 30.        ]]])

In [233]:
d.ndim

3

In [234]:
d.shape

(2, 6, 4)

In [236]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

np.concatenate((a, b.T), axis=1)


array([[1, 2, 5],
       [3, 4, 6]])

In [237]:
np.r_[24:40,81,71]

array([24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 81,
       71])

In [238]:
np.c_[np.arange(24),np.arange(24),np.arange(24)]

array([[ 0,  0,  0],
       [ 1,  1,  1],
       [ 2,  2,  2],
       [ 3,  3,  3],
       [ 4,  4,  4],
       [ 5,  5,  5],
       [ 6,  6,  6],
       [ 7,  7,  7],
       [ 8,  8,  8],
       [ 9,  9,  9],
       [10, 10, 10],
       [11, 11, 11],
       [12, 12, 12],
       [13, 13, 13],
       [14, 14, 14],
       [15, 15, 15],
       [16, 16, 16],
       [17, 17, 17],
       [18, 18, 18],
       [19, 19, 19],
       [20, 20, 20],
       [21, 21, 21],
       [22, 22, 22],
       [23, 23, 23]])

In [239]:
myArray = np.arange(24).reshape(6,4)

In [240]:
myArray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [241]:
np.split(myArray,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [243]:
np.split(myArray,6)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [249]:
np.vsplit(myArray,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [247]:
myArray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [260]:
d = np.array([[1,2,3],[4,5,6]])

In [262]:
e = d

In [263]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [264]:
e[0]=81

In [265]:
e

array([[81, 81, 81],
       [ 4,  5,  6]])

In [266]:
d

array([[81, 81, 81],
       [ 4,  5,  6]])

In [276]:
d.shape

(2, 3)

In [267]:
a = np.arange(24).reshape(2,3,4)
b = a.view()

In [268]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [269]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [273]:
a[0][0][0] = 123

In [274]:
a

array([[[123,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [275]:
b

array([[[123,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [277]:
a

array([[[123,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [278]:
np.ptp(a)

122

In [279]:
a = np.array([0, 1, 2, 3, 4])
a[[1, 3, 4]] = 0
a


array([0, 0, 2, 0, 0])

In [280]:
a = np.arange(12).reshape(3, 4)
b = a > 4
b  # `b` is a boolean with `a`'s shape

a[b]  # 1d array with the selected elements


array([ 5,  6,  7,  8,  9, 10, 11])

In [281]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [282]:
b = a[a>4]

In [283]:
b

array([ 5,  6,  7,  8,  9, 10, 11])